#!/usr/bin/env python3
import pika
import json
import time

connection = pika.BlockingConnection(pika.ConnectionParameters(host='rabbitmq'))
channel = connection.channel()
channel.queue_declare(queue='myQueue')
data = \
        {
                "id":1,
                "name": "My Name",
                "description":"This is desc about me"
        }

message = json.dumps(data)

while True:
    channel.basic_publish(exchange='',routing_key='myQueue',body=message)
    time.sleep(1)
    print(" [x] Sent 'Json Data From Writer Process!'")

connection.close()

